Vagrant.configure("2") do |config|
  BOX_NAME = "generic/debian12"
  # Uncomment to enable your local SSH key for provisioning automation (Ansible, etc)
  # config.ssh.insert_key = false
  # config.vm.provision "file",
  #  source: "~/.ssh/id_ed25519.pub",
  #  destination: "/home/vagrant/.ssh/authorized_keys"
  config.vm.provider :libvirt do |lv|
    lv.uri    = "qemu:///system"
    lv.memory = 2048
    lv.cpus   = 2
    lv.storage_pool_name = "vagrant_pool"
    lv.storage :file, :size => '20G', :type => 'raw', :bus => 'virtio'
    lv.nic_model_type = "virtio"
  end

  nodes = {
    "vm1" => "192.168.122.121",
    "vm2" => "192.168.122.122",
    "vm3" => "192.168.122.123",
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.box = BOX_NAME
      node.vm.hostname = name
      node.vm.provision "shell", inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      echo "nameserver 1.1.1.1" > /etc/resolv.conf
      apt-get update -y
      apt-get upgrade -y
      apt-get autoremove -y
    SHELL
      node.vm.network "private_network",
                      ip: ip,
                      libvirt__network_name: "vagrant_pool"

      node.vm.synced_folder ".", "/vagrant",
                             type: "rsync",
                             rsync__exclude: [".git/", ".vagrant/"]

    end
  end
end
