Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian12"
  
    config.vm.network "private_network",
                      ip: "192.168.122.121",
                      libvirt__network_name: "default"
  
    config.vm.synced_folder ".", "/vagrant",
                             type: "rsync",
                             rsync__exclude: [".git/", ".vagrant/"]
  
    config.vm.provider :libvirt do |lv|
      lv.uri    = "qemu:///system"
      lv.memory = 2048
      lv.cpus   = 2
    end
  end
  